
name: ðŸš€ðŸš€ðŸš€ Launch PR creator ðŸ“¢ðŸ“¢ðŸ“¢
on:
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create temporary branch
        run: | 
          branch_name= 'temp-branch-%m-%d-%Y-%H-%M-%S'
          git checkout -b "$branch_name"
          echo "::set-output name=branch_name::$branch_name"


      - name: Create and commit text file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "This is a sample text file." > sample.txt
          git add sample.txt
          git commit -m "Add sample.txt"
          
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          title: 'Mona the Octocat'
          body: 'Mona the octocat welcomes you to this repository!'
          head: ${{ steps.create_branch.outputs.branch_name }}
          base: 'main'
          labels: 'bug, enhancement'
          assignees: 'elopezanaya'
          reviewers: 'elopezanaya'
          team_reviewers: 'elopezanaya'
          owner: 'elopezanaya'
          repo: 'cit-gh-actions'
          token: ${{ secrets.GITHUB_TOKEN }}
          author: 'octocat'
          auto-merge: 'true'
                # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
